-- 1. Profiles Table
CREATE TABLE profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    full_name TEXT,
    email TEXT,
    avatar_url TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Function to handle new user signups and insert into profiles automatically
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, phone)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email, new.raw_user_meta_data->>'phone');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Lost Items Table
CREATE TABLE lost_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    color TEXT,
    size TEXT,
    date_lost DATE,
    location TEXT,
    city TEXT,
    state TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    reward NUMERIC DEFAULT 0,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Found Items Table
CREATE TABLE found_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    color TEXT,
    size TEXT,
    date_found DATE,
    location TEXT,
    city TEXT,
    state TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    condition TEXT DEFAULT 'Good',
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Complaints Table
CREATE TABLE complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 5. Messages Table
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES profiles(id),
    receiver_id UUID REFERENCES profiles(id),
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 6. Whitelist Table (Admin Access)
CREATE TABLE whitelist (
    user_id UUID REFERENCES profiles(id) PRIMARY KEY,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE lost_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE found_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE whitelist ENABLE ROW LEVEL SECURITY;

-- Temporary: Allow all read/write access for easy setup. 
-- In production, you would lock this down (e.g. users can only edit their own items).
CREATE POLICY "Allow all read" ON profiles FOR SELECT USING (true);
CREATE POLICY "Allow all write" ON profiles FOR ALL USING (true);

CREATE POLICY "Allow all read" ON lost_items FOR SELECT USING (true);
CREATE POLICY "Allow all write" ON lost_items FOR ALL USING (true);

CREATE POLICY "Allow all read" ON found_items FOR SELECT USING (true);
CREATE POLICY "Allow all write" ON found_items FOR ALL USING (true);

CREATE POLICY "Allow all read" ON complaints FOR SELECT USING (true);
CREATE POLICY "Allow all write" ON complaints FOR ALL USING (true);

CREATE POLICY "Allow all read" ON messages FOR SELECT USING (true);
CREATE POLICY "Allow all write" ON messages FOR ALL USING (true);

CREATE POLICY "Allow all read" ON whitelist FOR SELECT USING (true);
CREATE POLICY "Allow all write" ON whitelist FOR ALL USING (true);

-- Create Storage Bucket for Item Images
INSERT INTO storage.buckets (id, name, public) VALUES ('item-images', 'item-images', true) ON CONFLICT DO NOTHING;
